### ISSUE TITLE
Pressing tab does not bring focus to theme toggle.

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell-starter-minima#1]
In https://abell-starter-minima.netlify.app, Pressing tab does not add focus to the toggle in the top right corner. This makes it impossible for the people who are navigating through a keyboard to change the theme.

![Screenshot of dark theme toggle from website](https://user-images.githubusercontent.com/30949385/81471063-1ce11f80-920c-11ea-9149-0dca7178cc55.png)

The code behind the index and content is in, [src/index.abell](https://github.com/abelljs/abell-starter-minima/blob/master/src/index.abell) and [src/template/content.abell](https://github.com/abelljs/abell-starter-minima/blob/master/src/template/content.abell)

**Comment by dr5hn** [comment]
@saurabhdaware 
It's little bit tricky to apply a tabindex to hidden element.

From inspecting your code and applying a tabindex to label. It only focuses label on tab. Since we also need a toggle event on any key press.
<img width="948" alt="Screenshot 2020-05-09 at 7 18 57 PM" src="https://user-images.githubusercontent.com/6929121/81475492-35f8c900-922a-11ea-8568-d139a7b3d2b0.png">

I found some ref link that can help you achieve that ::
https://stackoverflow.com/questions/3537596/forcing-a-tab-stop-on-a-hidden-element-possible
https://fuzzbomb.github.io/accessibility-demos/visually-hidden-focus-test.html

**Comment by saurabhdaware** [comment]
Oh, thank you so much! This will help. I'll try it out.
